#!/bin/zsh
[ ! -x ./configure ]	|| rm -f configure
[ ! -d autom4te.cache ]	|| rm -rf autom4te.cache
rm -f configure autom4*
./autogen.sh --help
configure conky								\
	--enable-audacious=yes						\
	--enable-iostats						\
	--enable-curl							\
	--enable-rss							\
	--enable-xoap							\
	--enable-weather						\
	--enable-weather-metar						\
	--enable-weather-xoap						\
	--enable-imlib2							\
	--enable-lua-imlib2						\
	--enable-lua							\
	--enable-lua-cairo						\
	--enable-lua-extras						\
	--enable-wlan							\
	"$@"
