#!/bin/zsh
# vim: ts=8 sw=8 noet

configure -m "xchat"							\
	--disable-nls							\
	--enable-threads=posix						\
	--enable-gtkfe							\
	--enable-textfe							\
	--enable-perl							\
	--enable-perl_old						\
	--enable-shm							\
	--enable-spell=gtkspell						\
	--with-gnu-ld							\
	--enable-tcl=/usr/lib64						\
	"$@"
