#!/bin/zsh
# vim: ts=8 sw=8 noet
if [[ -x /bin/pump ]]; then
	# If we have pump(1) available, do its initialization now and
	# register an exit function to gracefully shut it down.  This
	# is so-o-o cool!
	eval $( /bin/pump --startup )
	zshexit()       {
		echo 'bye'
		/bin/pump --shutdown
		echo 'gone...'
	}
fi
if [[ -f configure ]]; then
	autoreconf -fvim
else
	configure -m 'haveged'						\
	"$@"
fi
