#!/bin/zsh
# vim: ts=8 sw=8
configure -m -n e16							\
									\
	--prefix=/							\
	--with-x							\
	--with-gnu-ld							\
	--disable-nls							\
	--enable-composite						\
	--enable-modules						\
	--enable-modules						\
	--enable-pango							\
	--enable-silent-rules						\
	--enable-sound							\
									\
	"$@"
make dist
exit $?
	--enable-pseudotrans						\
	--enable-sound-esound						\
	--enable-sound-pulse						\
