#!/bin/zsh
rm -f configure autom4*
exec configure pidgin                           \
    --disable-nls                               \
    --disable-nm                                \
    --disable-avahi                             \
    --disable-perl                              \
    --disable-tcl                               \
    --with-gtk=2                                \
    $@
# NOTREACHED
    --disable-meanwhile                     \
    --disable-idn                           \
    -disable-vv                            \
