#!/bin/zsh
# vim: sw=8 ts=8

OPTS=
PKG=$0-opts-$(basename ${PWD})
# echo "PKG=${PKG}"; exit 1; FIXME
if [ -f ${PKG} ]; then
	OPTS=$(< ${PKG})
fi

# echo "OPTS=$OPTS"; exit 1; FIXME

rm -rf configure autom4te.cache

configure faces								\
	CC='ccache gcc'							\
	CFLAGS='-pipe -Os'						\
	CPPFLAGS="${CPPFLAGS} -Wall -pedantic"				\
	LDFLAGS="${LDFLAGS}"						\
	--disable-nls							\
	--enable-threads=posix						\
	--enable-audio							\
	--enable-dns-lookup						\
	--enable-imap							\
	--enable-pop							\
	${OPTS}								\
	"$@"
