#!/bin/sh
# vim: sw=8 ts=8 noet

rm -f configure

./Util/preconfig

if [[ -x /bin/pump ]]; then
	eval $( /bin/pump --startup )
	ZSHEXIT()	{
		/bin/pump --shutdown
	}
fi

# configure -m -d zsh							\
configure -m								\
	--								\
	--enable-maildir-support					\
	--enable-cap							\
	"$@"
exit 0
	--enable-zsh-mem						\
