#!/bin/zsh
# vim: ts=8 sw=8 noet
if [[ -f configure ]]; then
	# ./configure --without-x --without-xft --without-gnome --with-gcc
	./configure --with-x --with-xft --without-gnome --with-gcc
	[[ -x /bin/pump ]] && pump make -j10 || make -j10
else
	echo "You been messing about and deleted the distro 'configure' file." >&2
	exit( 1 )
fi
