#!/bin/zsh
[ ! -x ./configure ]	|| rm -f configure
[ ! -d autom4te.cache ]	|| rm -rf autom4te.cache
[ ! -f config.status ]  || rm -rf config.status
rm -f configure autom4* config.status
./autogen.sh --help
configure conky								\
	--disable-otr							\
	--enable-ssl=openssl						\
	--with-gnu-ld							\
	"$@"
make -j9
exit 0
	--enable-ssl=gnutls+openssl					\
	--enable-autopackage						\
