#!/bin/zsh
# vim: noet sw=8 ts=8
rm -rf ***/configure ***/autom4* **/Makefile
./autogen.sh								\
	--prefix=/opt/pidgin						\
	--disable-nls							\
	--disable-consoleui						\
	--disable-nm							\
	--with-gtk=2							\
	--disable-kwallet						\
	--enable-cap							\
	--enable-mono							\
	--enable-nss							\
	--with-x							\
	$@
make
exit 1

exec configure pidgin							\
	--disable-nls							\
	--disable-consoleui						\
	--disable-nm							\
	--with-gtk=2							\
	--disable-kwallet						\
	--enable-cap							\
	--enable-mono							\
	--enable-nss							\
	--with-x							\
	$@

# NOTREACHED
	--disable-meanwhile						\
	--disable-idn							\
	-disable-vv							\
	--disable-perl							\
	--disable-tcl							\
	--disable-avahi							\
	--enable-gcr							\
