#!/bin/zsh
# vim: ts=8 sw=8 noet
if [[ -f configure && -f config.status ]]; then
	autoreconf -fvim
else
	rm -f configure config.status
	configure -m 'xterm'						\
	--with-pkg-config						\
	--with-Xaw3d							\
	--disable-imake							\
	--enable-double-buffer						\
	"$@"
fi
exit $?

`configure' configures this package to adapt to many kinds of systems.

Usage: ./configure [OPTION]... [VAR=VALUE]...

To assign environment variables (e.g., CC, CFLAGS...), specify them as
VAR=VALUE.  See below for descriptions of some of the useful variables.

Defaults for the options are specified in brackets.

Configuration:
  -h, --help              display this help and exit
      --help=short        display options specific to this package
      --help=recursive    display the short help of all the included packages
  -V, --version           display version information and exit
  -q, --quiet, --silent   do not print `checking...' messages
      --cache-file=FILE   cache test results in FILE [disabled]
  -C, --config-cache      alias for `--cache-file=config.cache'
  -n, --no-create         do not create output files
      --srcdir=DIR        find the sources in DIR [configure dir or `..']

Installation directories:
  --prefix=PREFIX         install architecture-independent files in PREFIX
                          [/usr/local]
  --exec-prefix=EPREFIX   install architecture-dependent files in EPREFIX
                          [PREFIX]

By default, `make install' will install all the files in
`/usr/local/bin', `/usr/local/lib' etc.  You can specify
an installation prefix other than `/usr/local' using `--prefix',
for instance `--prefix=$HOME'.

For better control, use the options below.

Fine tuning of the installation directories:
  --bindir=DIR            user executables [EPREFIX/bin]
  --sbindir=DIR           system admin executables [EPREFIX/sbin]
  --libexecdir=DIR        program executables [EPREFIX/libexec]
  --datarootdir=DIR       read-only architecture-independent data [PREFIX/share]
  --datadir=DIR           read-only architecture-independent data [DATAROOTDIR]
  --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
  --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
  --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
  --libdir=DIR            object code libraries [EPREFIX/lib]
  --includedir=DIR        C header files [PREFIX/include]
  --oldincludedir=DIR     C header files for non-gcc [/usr/include]
  --infodir=DIR           info documentation [DATAROOTDIR/info]
  --mandir=DIR            man documentation [DATAROOTDIR/man]

Program names:
  --program-prefix=PREFIX            prepend PREFIX to installed program names
  --program-suffix=SUFFIX            append SUFFIX to installed program names
  --program-transform-name=PROGRAM   run sed PROGRAM on installed program names

X features:
  --x-includes=DIR    X include files are in DIR
  --x-libraries=DIR   X library files are in DIR

System types:
  --build=BUILD           configure for building on BUILD [guessed]
  --host=HOST       build programs to run on HOST [BUILD]

Optional Features:
  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]

Optional Packages:
  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)

Compile/Install Options:
  --disable-full-tgetent  disable check for full tgetent function
  --with-app-class=XXX    override X applications class (default XTerm)
  --with-app-defaults=DIR directory in which to install resource files (EPREFIX/lib/X11/app-defaults)
  --with-icon-name=XXXX   override icon name (default: xterm-color)
  --with-icon-symlink=XXX make symbolic link for icon name (default: xterm)
  --with-pixmapdir=DIR    directory in which to install pixmaps (DATADIR/pixmaps)
  --with-icondir=DIR      directory in which to install icons for desktop
  --with-icon-theme=XXX   install icons into desktop theme (hicolor)
  --disable-desktop       disable install of xterm desktop files
  --with-desktop-category=XXX  one or more desktop catgories or auto
  --with-reference=XXX    program to use as permissions-reference
  --with-xterm-symlink=XXX make symbolic link to installed xterm
  --disable-openpty       disable openpty, prefer other interfaces
  --disable-setuid        disable setuid in xterm, do not install setuid/setgid
  --disable-setgid        disable setgid in xterm, do not install setuid/setgid
  --with-setuid=XXX       use the given setuid user
  --with-utmp-setgid=XXX  use setgid to match utmp/utmpx file
  --with-utempter         use utempter library for access to utmp
  --with-tty-group=XXX    use XXX for the tty-group
  --with-x                use the X Window System
  --with-pkg-config{=path} enable/disable use of pkg-config
  --with-xpm=DIR          use Xpm library for colored icon, may specify path
  --with-Xaw3d            link with Xaw 3d library
  --with-Xaw3dxft         link with Xaw 3d xft library
  --with-neXtaw           link with neXT Athena library
  --with-XawPlus          link with Athena-Plus library
  --enable-narrowproto    enable narrow prototypes for X libraries
  --disable-imake         disable use of imake for definitions
  --with-man2html=XXX     use XXX rather than groff
Terminal Configuration:
  --with-terminal-id=V    set default decTerminalID (default: vt420)
  --with-terminal-type=T  set default $TERM (default: xterm)
  --enable-backarrow-key  set default backarrowKey resource (default: true)
  --enable-backarrow-is-erase set default backarrowKeyIsErase resource (default: false)
  --enable-delete-is-del  set default deleteIsDEL resource (default: maybe)
  --enable-pty-erase      set default ptyInitialErase resource (default: maybe)
  --enable-alt-sends-esc  set default altSendsEscape resource (default: no)
  --enable-meta-sends-esc set default metaSendsEscape resource (default: no)
  --with-own-terminfo=P   set default $TERMINFO (default: from environment)
Optional Features:
  --disable-active-icon   disable X11R6.3 active-icon feature
  --disable-ansi-color    disable ANSI color
  --disable-16-color      disable 16-color support
  --enable-256-color      enable 256-color support
  --enable-88-color       enable 88-color support
  --disable-blink-cursor  disable support for blinking cursor
  --enable-broken-osc     allow broken Linux OSC-strings
  --disable-broken-st     disallow broken string-terminators
  --enable-builtin-xpms   compile-in icon data
  --disable-c1-print      disallow -k8 option for printable 128-159
  --disable-bold-color    disable PC-style mapping of bold colors
  --disable-color-class   disable separate color class resources
  --disable-color-mode    disable default colorMode resource
  --disable-highlighting  disable support for color highlighting
  --disable-doublechars   disable support for double-size chars
  --disable-boxchars      disable fallback-support for box chars
  --enable-exec-xterm     enable "spawn-new-terminal" action
  --enable-double-buffer  enable double-buffering
  --disable-freetype      disable freetype library-support
  --with-freetype-config  configure script to use for FreeType
  --with-freetype-cflags  -D/-I options for compiling with FreeType
  --with-freetype-libs    -L/-l options to link FreeType
  --enable-hp-fkeys       enable support for HP-style function keys
  --enable-sco-fkeys      enable support for SCO-style function keys
  --disable-sun-fkeys     disable support for Sun-style function keys
  --disable-fifo-lines    disable FIFO-storage for saved-lines
  --disable-i18n          disable internationalization
  --disable-initial-erase disable setup for stty erase
  --disable-input-method  disable input-method
  --enable-load-vt-fonts  enable load-vt-fonts() action
  --enable-logging        enable logging
  --enable-logfile-exec   enable exec'd logfile filter
  --disable-maximize      disable actions for iconify/deiconify/maximize/restore
  --disable-num-lock      disable NumLock keypad support
  --disable-paste64       disable get/set base64 selection data
  --disable-pty-handshake disable pty-handshake support
  --enable-readline-mouse enable support for mouse in readline applications
  --disable-regex         disable regular-expression selections
  --with-pcre             use PCRE for regular-expressions
  --disable-rightbar      disable right-scrollbar support
  --disable-samename      disable check for redundant name-change
  --disable-selection-ops disable selection-action operations
  --disable-session-mgt   disable support for session management
  --disable-tcap-fkeys    disable termcap function-keys support
  --disable-tcap-query    disable compiled-in termcap-query support
  --disable-tek4014       disable tek4014 emulation
  --enable-toolbar        compile-in toolbar for pulldown menus
  --disable-vt52          disable VT52 emulation
  --disable-wide-attrs    disable wide-attribute support
  --disable-wide-chars    disable wide-character support
  --enable-16bit-chars    enable 16-bit character support
  --enable-mini-luit      enable mini-luit (built-in Latin9 support)
  --disable-luit          enable luit filter (Unicode translation)
  --enable-dabbrev        enable dynamic-abbreviation support
  --enable-dec-locator    enable DECterm Locator support
  --enable-regis-graphics enable ReGIS graphics support
  --enable-sixel-graphics enable sixel graphics support
  --disable-rectangles    disable VT420 rectangle support
  --disable-ziconbeep     disable -ziconbeep option
Testing/development Options:
  --enable-trace          test: set to enable debugging traces
  --with-dmalloc          test: use Gray Watson's dmalloc library
  --with-dbmalloc         test: use Conor Cahill's dbmalloc library
  --with-valgrind         test: use valgrind
  --disable-leaks         test: free permanent memory, analyze leaks
  --disable-echo          do not display "compiling" commands
  --enable-xmc-glitch     test: enable xmc magic-cookie emulation
  --enable-warnings       test: turn on GCC compiler warnings
  --disable-rpath-hack    don't add rpath options for additional libraries

Some influential environment variables:
  CC          C compiler command
  CFLAGS      C compiler flags
  LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
              nonstandard directory <lib dir>
  CPPFLAGS    C/C++ preprocessor flags, e.g. -I<include dir> if you have
              headers in a nonstandard directory <include dir>
  CPP         C preprocessor

Use these variables to override the choices made by `configure' or to help
it to find libraries and programs with nonstandard names/locations.

