#!/bin/zsh
./bootstrap.sh
configure -m -n mrxvt							\
	--enable-everything						\
	--enable-maintainer-mode					\
	--with-tab-radius=300						\
	--with-save-lines=5000						\
	--with-atab-extra=25						\
	--enable-xft							\
	--enable-menubar						\
	--enable-24bits							\
	--enable-frills							\
	--prefix=/opt/mrxvt
