#!/bin/zsh
rm -rf configure autom4te.cache
./autogen.sh --prefix=/opt/sylpheed					\
	--enable-ldap							\
	--enable-threads						\
	--enable-oniguruma						\
	--disable-ipv6							\
	"$@"
make -j10
exit 0
