#!/bin/zsh
# vim: ts=8 sw=8 noet
if [[ -f configure ]]; then
	autoreconf -fvi
	[[ -x /bin/pump ]] && pump make -j10 || make -j10
else
	configure -m 'eviacam'						\
		--disable-nls						\
		--enable-silent-rules					\
		--with-wx-config=wx-config				\
		"$@"
fi
exit 0
		--with-wx-config=wx-config-3.0-gtk2			\
