#!/bin/zsh
[ -d src ] && cd src
[ -d autom4cache ] && rm -rf autom4cache
[ -d auto ] && rm -rf auto/config.cache
mkdir -p auto
rm -f configure
configure -m vim							\
	--enable-cscope							\
	--enable-gtk2-check						\
	--enable-gnome-check						\
	--enable-motif-check						\
	--enable-athena-check						\
	--enable-nextaw-check						\
	--enable-fontset						\
	--enable-gui=gtk2						\
	--enable-luainterp=yes						\
	--enable-pythoninterp=yes					\
	--enable-rubyinterp=yes						\
	--enable-perlinterp=yes						\
	--enable-sniff							\
	--enable-tclinterp						\
	--with-features=huge						\
	CFLAGS='-pipe -g -Os -D_FORTIFY_SOURCE=1'			\
	"$@"
exit
	--disable-athena-check						\
	--disable-nextaw-check						\
	--enable-gnome-check						\
	--enable-perlinterp=dynamic					\
