#!/bin/zsh
[[ -d src ]] && cd src
[[ -d autom4cache ]] && rm -rf autom4cache
[[ -d auto ]] && rm -rf auto/config.cache
mkdir -p auto
rm -f configure
configure vim								\
	--with-features=huge						\
	--enable-pythoninterp=yes					\
	--enable-tclinterp						\
	--enable-rubyinterp=yes						\
	--enable-luainterp=yes						\
	--enable-sniff							\
	--enable-fontset						\
	--disable-netbeans						\
	--enable-gui=auto						\
	CFLAGS='-pipe -g -Os -D_FORTIFY_SOURCE=1'			\
	"$@"
pump make -j10
exit
	--enable-cscope							\
	--disable-nextaw-check						\
	--enable-perlinterp=dynamic					\
	--enable-gui=nextaw						\
	--enable-neXtaw-check						\
	--enable-motif-check						\
	--enable-gui=athena						\
	--enable-athena-check						\
	--enable-gui=gtk2						\
	--enable-gtk2-check						\
	--enable-gnome-check						\
	--enable-gui=gnome						\
