#!/bin/zsh
rm -f configure
exec configure pidgin							\
	--disable-perl							\
	$@
# NOTREACHED
	--disable-tcl							\
	--disable-avahi							\
	--disable-meanwhile						\
	--disable-idn							\
	--disable-nm							\
	--disable-vv							\
